export const COLORS = {
  background: '#F9F9FF',
  textPrimary: '#FFFFFF',
  textSecondary: 'rgba(255, 255, 255, 0.9)',
  logoGlow: 'rgba(255, 255, 255, 0.4)',
  accent: '#05B0DF',
  accentGlow: 'rgba(5, 176, 223, 0.1)',
  accentGlowSoft: 'rgba(5, 176, 223, 0.12)',
  limeGlow: 'rgba(180, 242, 99, 0.05)',
  splashBackground: '#F8FAFC',
  splashGradientTopLeft: '#E8F9FD',
  splashGradientCenter: '#F8FCFD',
  splashGradientBottomRight: '#F1F9E8',
  splashGarmentFill: '#FFFFFF',
  splashGarmentStroke: '#05B0DF',
  splashAccentGreen: '#91CC42',
  splashSparkleBlue: 'rgba(5, 176, 223, 0.55)',
  splashSparkleWhite: 'rgba(255, 255, 255, 0.95)',
  splashTitle: '#111C2D',
  splashSubtitle: '#3D484E',
  dotInactive: '#D8E3FB',
  headingText: '#111C2D',
  bodyText: '#3D484E',
  skipText: '#006783',
  onboarding2Background: '#EBF9FF',
  onboarding2SkipText: '#3D484E',
  onboarding2CircleGlow: 'rgba(189, 233, 255, 0.2)',
  onboarding2DotActiveGlow: 'rgba(5, 176, 223, 0.4)',
  onboarding3Background: '#EBF9FF',
  onboarding3DotInactive: '#BCC8CF',
  loginGradientTop: 'rgba(189, 233, 255, 0.5)',
  loginGradientBottom: 'rgba(255, 255, 255, 0)',
  loginHeading: '#191C1E',
  loginSubtitle: '#3D484E',
  loginInputBg: '#F7F9FB',
  loginInputBorder: '#BCC8CF',
  loginInputDivider: 'rgba(188, 200, 207, 0.5)',
  loginPlaceholder: 'rgba(109, 121, 127, 0.7)',
  loginFooterText: '#6D797F',
  loginFooterLink: '#006783',
  otpHeading: '#191C1E',
  otpSubtitle: '#6D797F',
  otpEmail: '#191C1E',
  otpInputBg: '#F7F9FB',
  otpInputBorder: '#BCC8CF',
  otpInputActiveBorder: '#2563EB',
  otpAccentText: '#006783',
  homeHeaderBg: '#F7F9FB',
  homeLocationLabel: '#3D484E',
  homeLocationValue: '#006783',
  homeGreeting: '#191C1E',
  homeSubtitle: '#6D797F',
  homeSearchBorder: '#E0E3E5',
  homeSearchPlaceholder: '#6B7280',
  homeSearchIcon: '#6D797F',
  homeBannerButtonBg: '#416900',
  homeSectionHeading: '#191C1E',
  homeCardCircle: 'rgba(189, 233, 255, 0.3)',
  homeCardAlt: '#FDFCFC',
  homeCardAlt2: '#FCFCFC',
  homeIconBoxBg: '#ECEEF0',
  homeOrderSubtitle: '#6D797F',
  homeBadgeProgressBg: 'rgba(192, 242, 130, 0.3)',
  homeBadgeProgressText: '#416903',
  homeBadgeDeliveredBg: '#E0E3E5',
  homeBadgeDeliveredText: '#3D484E',
  homeNavBg: 'rgba(137, 198, 59, 0.1)',
  homeNavBorder: '#BCC8CF',
  homeCarouselDotActive: '#1696E0',
  homeCarouselDotInactive: '#CCDADC',
  homeUnderlineAccent: '#80BE3C',
  homeServiceCardBorderBlue: '#CEE8F9',
  homeServiceCardBorderGreen: '#EDF6E3',
  homeServiceCardCircleBlue: '#E5F4FE',
  homeServiceCardCircleGreen: '#EDF6E3',
  homeServiceCardLabel: '#191C1E',
  homeScheduleGradientStart: '#05B0DF',
  homeScheduleGradientEnd: '#84BF3F',
  homeScheduleButtonText: '#FFFFFF',
  homeOrderIdLabel: '#707E97',
  homeOrderNumber: '#191C1E',
  homeOrderAccentInProgress: '#7DC121',
  homeOrderAccentDelivered: '#0074C9',
  homeOrderDivider: '#E8E9EC',
  homeOrderCaptionLabel: '#6D797F',
  homeOrderCaptionValue: '#000000',
  homeStatusInProgressBg: '#E6F7D7',
  homeStatusInProgressText: '#236E03',
  homeStatusDeliveredBg: '#DBECFC',
  homeStatusDeliveredText: '#045FC0',
  areaHeaderBg: '#F7F9FB',
  areaHeaderTitle: '#006783',
  areaCloseIcon: '#006783',
  areaSearchBorder: '#BCC8CF',
  areaSearchPlaceholder: '#6D797F',
  areaSearchIcon: '#BCC8CF',
  areaListBorder: '#E7EEFF',
  areaItemText: '#111C2D',
  areaChevron: '#BCC8CF',
  areaDivider: 'rgba(188, 200, 207, 0.3)',
  storeHeaderTitle: '#006783',
  storeBackIcon: '#3D484E',
  storeName: '#191C1E',
  storeAddress: '#3D484E',
  storeBadgeBg: 'rgba(5, 176, 223, 0.1)',
  storeBadgeText: '#05B0DF',
  storePickupText: '#3D484E',
  servicesHeaderTitle: '#006783',
  servicesBackIcon: '#006783',
  servicesListBorder: '#E6E8EA',
  servicesName: '#191C1E',
  servicesDescription: '#3D484E',
  servicesChevron: '#BCC8CF',
  serviceDetailHeaderTitle: '#006783',
  serviceDetailBackIcon: '#006783',
  serviceDetailHeaderBg: '#F7F9FB',
  serviceDetailBannerBorder: 'rgba(0, 0, 0, 0.05)',
  serviceDetailCategoryActiveBg: '#05B0DF',
  serviceDetailCategoryInactiveBg: '#F9F9FF',
  serviceDetailCategoryInactiveBorder: '#BCC8CF',
  serviceDetailCategoryInactiveText: '#3D484E',
  serviceDetailCategoryActiveText: '#FFFFFF',
  serviceDetailGenderActiveBg: '#05B0DF',
  serviceDetailGenderActiveText: '#FFFFFF',
  serviceDetailGenderInactiveBorder: '#BCC8CF',
  serviceDetailGenderInactiveText: '#3D484E',
  serviceDetailItemCardBg: '#FFFFFF',
  serviceDetailItemName: '#111C2D',
  serviceDetailItemDescription: '#6D797F',
  serviceDetailItemPrice: '#05B0DF',
  serviceDetailAddButtonBorder: '#05B0DF',
  serviceDetailAddButtonText: '#05B0DF',
  serviceDetailCheckoutBg: '#05B0DF',
  serviceDetailCheckoutText: '#FFFFFF',
  cartHeaderTitle: '#006783',
  cartHeaderBg: '#F7F9FB',
  cartItemName: '#191C1E',
  cartItemDescription: '#3D484E',
  cartItemPrice: '#006783',
  cartStepperBg: '#05B0DF',
  cartInputBg: '#F7F9FB',
  cartInputBorder: '#BCC8CF',
  cartInputPlaceholder: '#6B7280',
  cartSummaryLabel: '#3D484E',
  cartSummaryValue: '#191C1E',
  cartDiscountBg: 'rgba(145, 204, 66, 0.1)',
  cartDiscountText: '#91CC42',
  cartDivider: '#BCC8CF',
  cartTotalLabel: '#191C1E',
  cartTotalValue: '#05B0DF',
  cartEmptyHeading: '#191C1E',
  cartEmptySubtitle: '#3D484E',
  cartEmptyButtonBg: '#05B0DF',
  cartEmptyButtonText: '#FFFFFF',

  addressHeaderBg: '#F7F9FB',
  addressHeaderTitle: '#006783',
  addressMapBg: '#E6E8EA',
  addressPinBg: '#006783',
  addressCurrentLocationText: '#006783',
  addressSectionTitle: '#191C1E',
  addressCardBorder: '#006783',
  addressCardActiveIconBg: 'rgba(5, 176, 223, 0.2)',
  addressCardInactiveIconBg: '#ECEEF0',
  addressCardInactiveIcon: '#6D797F',
  addressName: '#191C1E',
  addressDefaultBadgeBg: '#E6E8EA',
  addressDefaultBadgeText: '#3D484E',
  addressText: '#3D484E',
  addressEditIcon: '#6D797F',
  addressSelectedBadgeBg: '#006783',
  addressSelectedBadgeText: '#FFFFFF',
  addressAddBorder: '#BCC8CF',
  addressAddText: '#006783',
  addressConfirmBg: '#05B0DF',
  addressConfirmText: '#FFFFFF',

  addAddressHeaderBg: '#F7F9FB',
  addAddressHeaderTitle: '#006783',
  addAddressMapBg: '#E6E8EA',
  addAddressPinBg: '#006783',
  addAddressCurrentLocationText: '#006783',
  addAddressBorder: '#E0E3E5',
  addAddressCardTitle: '#191C1E',
  addAddressLocationContextBg: '#F2F4F6',
  addAddressLocationPrimaryText: '#191C1E',
  addAddressLocationSecondaryText: '#6D797F',
  addAddressFieldLabel: '#3D484E',
  addAddressInputBg: '#F7F9FB',
  addAddressInputReadonlyBg: '#F2F4F6',
  addAddressInputBorder: '#E0E3E5',
  addAddressInputPlaceholder: '#6B7280',
  addAddressInputText: '#191C1E',
  addAddressInputReadonlyText: '#3D484E',
  addAddressSeparator: '#E0E3E5',
  addAddressPillBg: '#F7F9FB',
  addAddressPillBorder: '#E0E3E5',
  addAddressPillText: '#3D484E',
  addAddressPillActiveBg: '#B4F263',
  addAddressPillActiveText: '#446E00',
  addAddressSaveBg: '#05B0DF',
  addAddressSaveText: '#FFFFFF',

  scheduleHeaderBg: '#F7F9FB',
  scheduleHeaderTitle: '#006783',
  scheduleSectionTitle: '#191C1E',
  scheduleDateInactiveBg: '#FFFFFF',
  scheduleDateInactiveBorder: '#E0E3E5',
  scheduleDateInactiveText: '#3D484E',
  scheduleDateActiveBg: '#05B0DF',
  scheduleDateActiveText: '#FFFFFF',
  scheduleSlotInactiveBg: '#FFFFFF',
  scheduleSlotInactiveBorder: '#E0E3E5',
  scheduleSlotInactiveText: '#191C1E',
  scheduleSlotActiveBg: '#05B0DF',
  scheduleSlotActiveText: '#FFFFFF',
  scheduleToggleIconBg: 'rgba(180, 242, 99, 0.2)',
  scheduleToggleIcon: '#82B049',
  scheduleToggleTitle: '#191C1E',
  scheduleToggleSubtitle: '#3D484E',
  scheduleSwitchOffBg: '#E0E3E5',
  scheduleSwitchOnBg: '#05B0DF',
  scheduleSwitchThumb: '#FFFFFF',
  scheduleSwitchThumbBorder: '#D1D5DB',
  scheduleNotesOptional: '#3D484E',
  scheduleNotesInputBg: '#FFFFFF',
  scheduleNotesInputBorder: '#E0E3E5',
  scheduleNotesPlaceholder: '#6D797F',
  scheduleContinueBg: '#05B0DF',
  scheduleContinueText: '#FFFFFF',
  scheduleBottomBarBorder: '#E0E3E5',

  paymentHeaderBg: '#F7F9FB',
  paymentHeaderTitle: '#006783',
  paymentBackIcon: '#3D484E',
  paymentCardBorder: '#E0E3E5',
  paymentOrderTitle: '#191C1E',
  paymentOrderId: '#6D797F',
  paymentStatusBadgeBg: 'rgba(130, 176, 73, 0.2)',
  paymentStatusBadgeText: '#82B049',
  paymentLineItemLabel: '#3D484E',
  paymentLineItemValue: '#191C1E',
  paymentPromoText: '#416903',
  paymentDivider: '#E0E3E5',
  paymentTotalLabel: '#191C1E',
  paymentTotalValue: '#006783',
  paymentSectionTitle: '#191C1E',
  paymentMethodBg: '#FFFFFF',
  paymentMethodBorder: '#E0E3E5',
  paymentMethodActiveBg: 'rgba(5, 176, 223, 0.05)',
  paymentMethodActiveBorder: '#05B0DF',
  paymentMethodLabel: '#191C1E',
  paymentMethodDetail: '#6D797F',
  paymentIconWrapperBg: '#ECEEF0',
  paymentIconWrapperBorder: '#BCC8CF',
  paymentIcon: '#006783',
  paymentCardBadgeText: '#191C1E',
  paymentRadioBorder: '#BCC8CF',
  paymentRadioActiveBorder: '#05B0DF',
  paymentRadioActiveDot: '#05B0DF',
  paymentBottomBarBg: 'rgba(255, 255, 255, 0.9)',
  paymentBottomBarBorder: '#E0E3E5',
  paymentPayBg: '#05B0DF',
  paymentPayText: '#FFFFFF',

  orderConfirmedHeaderBg: '#F7F9FB',
  orderConfirmedCloseIcon: '#3D484E',
  orderConfirmedBadgeOuterFrom: '#05B0DF',
  orderConfirmedBadgeOuterTo: '#B4F263',
  orderConfirmedBadgeMidFrom: '#006783',
  orderConfirmedBadgeMidTo: '#416900',
  orderConfirmedBadgeInnerFrom: '#91CC42',
  orderConfirmedBadgeInnerTo: '#05B0DF',
  orderConfirmedBadgeRing: '#E0E3E5',
  orderConfirmedHeading: '#191C1E',
  orderConfirmedSubtitle: '#3D484E',
  orderConfirmedCardBorder: '#E6E8EA',
  orderConfirmedOrderLabel: '#3D484E',
  orderConfirmedOrderValue: '#006783',
  orderConfirmedDivider: '#E0E3E5',
  orderConfirmedInfoBoxBg: '#F7F9FB',
  orderConfirmedInfoLabel: '#3D484E',
  orderConfirmedInfoTitle: '#191C1E',
  orderConfirmedInfoSubtitle: '#3D484E',
  orderConfirmedTotalLabel: '#191C1E',
  orderConfirmedTotalValue: '#191C1E',
  orderConfirmedPrimaryBg: '#05B0DF',
  orderConfirmedPrimaryText: '#FFFFFF',
  orderConfirmedSecondaryText: '#006783',

  storeServicesHeaderBg: '#FFFFFF',
  storeServicesHeaderTitle: '#191C1E',
  storeServicesHeaderSubtitle: '#6D797F',
  storeServicesBackIcon: '#191C1E',
  storeServicesRatingStar: '#F5A623',
  storeServicesTabInactiveText: '#6D797F',
  storeServicesTabInactiveIcon: '#9AA5AB',
  storeServicesTabActiveText: '#FFFFFF',
  storeServicesTabActiveIcon: '#FFFFFF',
  storeServicesTabChipActiveBg: '#05B0DF',
  storeServicesTabChipInactiveBg: '#F2F4F6',
  storeServicesTabChipInactiveBorder: '#E6E8EA',
  storeServicesTabBorder: '#E6E8EA',
  storeServicesItemName: '#191C1E',
  storeServicesItemDesc: '#6D797F',
  storeServicesPrice: '#006783',
  storeServicesDivider: '#E6E8EA',
  storeServicesAddBg: '#FFFFFF',
  storeServicesAddBorder: '#05B0DF',
  storeServicesAddText: '#05B0DF',
  storeServicesStepperBg: '#05B0DF',
  storeServicesStepperIcon: '#FFFFFF',
  storeServicesStepperText: '#FFFFFF',
  storeServicesCartBarBg: '#006783',
  storeServicesCartBarText: '#FFFFFF',
  storeServicesCartBarSubtext: 'rgba(255, 255, 255, 0.8)',
  storeServicesCartButtonBg: '#05B0DF',
  storeServicesCartButtonText: '#FFFFFF',

  trackOrderHeaderBg: '#F7F9FB',
  trackOrderHeaderTitle: '#006783',
  trackOrderBackIcon: '#006783',
  trackOrderProfileIcon: '#000000',
  trackOrderSectionHeading: '#191C1E',
  trackOrderOrderId: '#3D484E',
  trackOrderBadgeBg: '#C0F282',
  trackOrderBadgeText: '#102000',
  trackOrderMapBg: '#F2F4F6',
  trackOrderMapBorder: '#E0E3E5',
  trackOrderEtaLabel: '#6D797F',
  trackOrderEtaValue: '#006783',
  trackOrderDriverCardBg: 'rgba(255, 255, 255, 0.9)',
  trackOrderDriverName: '#191C1E',
  trackOrderDriverRatingStar: '#416900',
  trackOrderDriverRatingText: '#3D484E',
  trackOrderCallButtonBg: '#05B0DF',
  trackOrderCallIcon: '#FFFFFF',
  trackOrderCardBg: '#FFFFFF',
  trackOrderCardBorder: '#ECEEF0',
  trackOrderCardHeading: '#191C1E',
  trackOrderDivider: '#E0E3E5',
  trackOrderStepTitle: '#191C1E',
  trackOrderStepSubtitle: '#6D797F',
  trackOrderStepActiveSubtitle: '#006783',
  trackOrderStepCompletedBg: '#006783',
  trackOrderStepCheckIcon: '#FFFFFF',
  trackOrderStepActiveBg: '#B4F263',
  trackOrderStepActiveDot: '#416900',
  trackOrderStepPendingBg: '#ECEEF0',
  trackOrderSupportCardBg: '#F2F4F6',
  trackOrderSupportCardBorder: '#E0E3E5',
  trackOrderSupportTitle: '#191C1E',
  trackOrderSupportSubtitle: '#3D484E',
  trackOrderSupportButtonBg: '#FFFFFF',
  trackOrderSupportButtonBorder: '#BCC8CF',
  trackOrderSupportButtonText: '#006783',
  trackOrderSupportButtonIcon: '#006783',

  orderHistoryHeaderBg: '#F7F9FB',
  orderHistoryHeaderTitle: '#006783',
  orderHistoryBackIcon: '#006783',
  orderHistoryProfileIcon: '#000000',
  orderHistoryChipActiveBg: '#05B0DF',
  orderHistoryChipActiveText: '#FFFFFF',
  orderHistoryChipInactiveBg: '#E6E8EA',
  orderHistoryChipInactiveText: '#3D484E',
  orderHistoryCardBg: '#FFFFFF',
  orderHistoryOrderNumber: '#191C1E',
  orderHistoryOrderMeta: '#6D797F',
  orderHistoryPrice: '#191C1E',
  orderHistoryPriceCancelled: '#BCC8CF',
  orderHistoryServiceIcon: '#6D797F',
  orderHistoryServiceLabel: '#3D484E',
  orderHistoryBadgeInProgressBg: '#BDE9FF',
  orderHistoryBadgeInProgressText: '#001F2A',
  orderHistoryBadgeCompletedBg: '#B4F263',
  orderHistoryBadgeCompletedText: '#446E00',
  orderHistoryBadgeCancelledBg: '#FFDAD6',
  orderHistoryBadgeCancelledText: '#93000A',
  orderHistoryViewDetailsBg: '#ECEEF0',
  orderHistoryViewDetailsBorder: '#BCC8CF',
  orderHistoryViewDetailsText: '#006783',
  orderHistoryTrackButtonBg: '#416900',
  orderHistoryTrackButtonText: '#FFFFFF',
  orderHistoryReorderButtonBg: '#006783',
  orderHistoryReorderButtonText: '#FFFFFF',

  profileHeaderBg: '#F7F9FB',
  profileHeaderTitle: '#006783',
  profileBackIcon: '#006783',
  profileHeaderProfileIcon: '#000000',
  profileCardBg: 'rgba(255, 255, 255, 0.9)',
  profileCardBorder: 'rgba(255, 255, 255, 0.2)',
  profileEditIcon: '#006783',
  profileName: '#191C1E',
  profilePhone: '#6D797F',
  profileBadgeBg: 'rgba(5, 176, 223, 0.1)',
  profileBadgeText: '#05B0DF',
  profileVerifiedBg: '#B4F263',
  profileVerifiedIcon: '#446E00',
  profileStatIconLoyaltyBg: 'rgba(130, 176, 73, 0.2)',
  profileStatIconLoyalty: '#416903',
  profileStatIconWalletBg: 'rgba(5, 176, 223, 0.2)',
  profileStatIconWallet: '#006783',
  profileStatLabel: '#6D797F',
  profileStatValue: '#191C1E',
  profileTrendText: '#416903',
  profileBannerIcon: '#006783',
  profileBannerTitle: '#191C1E',
  profileBannerSubtitle: '#6D797F',
  profileInviteBg: '#006783',
  profileInviteText: '#FFFFFF',
  profileSettingsCardBg: '#FFFFFF',
  profileSettingsDivider: 'rgba(224, 227, 229, 0.5)',
  profileSettingsHeading: '#191C1E',
  profileNavIconBg: '#E0E3E5',
  profileNavIcon: '#3D484E',
  profileNavLabel: '#191C1E',
  profileNavChevron: '#6D797F',
  profileNavDivider: 'rgba(224, 227, 229, 0.3)',
  profileLogoutIconBg: '#E0E3E5',
  profileLogoutIcon: '#BA1A1A',
  profileLogoutText: '#BA1A1A',
  profileFooterText: '#6D797F',

  supportHeaderBg: '#F7F9FB',
  supportHeaderTitle: '#006783',
  supportBackIcon: '#006783',
  supportHeaderProfileIcon: '#000000',
  supportHeading: '#191C1E',
  supportSubheading: '#3D484E',
  supportSearchBg: '#FFFFFF',
  supportSearchBorder: '#BCC8CF',
  supportSearchIcon: '#BCC8CF',
  supportSearchPlaceholder: '#6D797F',
  supportCategoryCardBg: '#FFFFFF',
  supportCategoryIconBg: 'rgba(5, 176, 223, 0.1)',
  supportCategoryIcon: '#006783',
  supportCategoryLabel: '#191C1E',
  supportTicketsCardBg: '#FFFFFF',
  supportTicketsHeading: '#191C1E',
  supportViewAllText: '#006783',
  supportTicketBorder: '#E0E3E5',
  supportTicketIconBg: '#E0E3E5',
  supportTicketIcon: '#3D484E',
  supportTicketTitle: '#191C1E',
  supportTicketSubtitle: '#3D484E',
  supportStatusInProgressBg: '#C0F282',
  supportStatusInProgressText: '#254000',
  supportStatusResolvedBg: '#ECEEF0',
  supportStatusResolvedText: '#3D484E',
  supportCtaCardBg: '#FFFFFF',
  supportCtaIconBg: 'rgba(5, 176, 223, 0.2)',
  supportCtaIcon: '#006783',
  supportCtaOnlineDotBg: '#B7F566',
  supportCtaTitle: '#191C1E',
  supportCtaSubtitle: '#3D484E',
  supportChatButtonBg: '#05B0DF',
  supportChatButtonText: '#FFFFFF',
  supportCallButtonBg: '#F7F9FB',
  supportCallButtonBorder: '#BCC8CF',
  supportCallButtonText: '#191C1E',
  supportEmailButtonText: '#006783',
  supportResponseTimeText: '#3D484E',

  notificationsHeaderBg: '#F7F9FB',
  notificationsHeaderTitle: '#006783',
  notificationsBackIcon: '#006783',
  notificationsHeaderProfileIcon: '#000000',
  notificationsHeading: '#191C1E',
  notificationsMarkAllText: '#006783',
  notificationsChipActiveBg: '#006783',
  notificationsChipActiveText: '#FFFFFF',
  notificationsChipInactiveBg: '#E6E8EA',
  notificationsChipInactiveText: '#3D484E',
  notificationsCardBg: '#FFFFFF',
  notificationsCardBorder: '#F2F4F6',
  notificationsIconBg: '#B4F263',
  notificationsIconColor: '#254000',
  notificationsTitle: '#191C1E',
  notificationsTime: '#6D797F',
  notificationsBody: '#3D484E',
  notificationsActionText: '#006783',

  settingsHeaderBg: '#F7F9FB',
  settingsHeaderTitle: '#006783',
  settingsBackIcon: '#006783',
  settingsHeaderProfileIcon: '#000000',
  settingsHeading: '#191C1E',
  settingsSubheading: '#3D484E',
  settingsSectionHeading: '#191C1E',
  settingsCardBg: '#FFFFFF',
  settingsCardBorder: '#ECEEF0',
  settingsRowDivider: '#ECEEF0',
  settingsIconBg: '#F2F4F6',
  settingsIconColor: '#006783',
  settingsRowTitle: '#191C1E',
  settingsRowSubtitle: '#3D484E',
  settingsChevron: '#BCC8CF',
  settingsSwitchOffBg: '#E0E3E5',
  settingsSwitchOnBg: '#05B0DF',
  settingsSwitchThumb: '#FFFFFF',
  settingsLogoutBg: 'rgba(255, 218, 214, 0.2)',
  settingsLogoutBorder: '#FFDAD6',
  settingsLogoutText: '#BA1A1A',
  settingsLogoutIcon: '#BA1A1A',
  settingsFooterText: '#BCC8CF',

  notFoundHeaderBg: '#F7F9FB',
  notFoundHeaderTitle: '#006783',
  notFoundBackIcon: '#006783',
  notFoundHeaderProfileIcon: '#000000',
  notFoundHeading: '#191C1E',
  notFoundSubtitle: '#3D484E',
  notFoundPrimaryBg: '#05B0DF',
  notFoundPrimaryText: '#FFFFFF',
  notFoundSecondaryBg: '#F7F9FB',
  notFoundSecondaryBorder: '#E2E8F0',
  notFoundSecondaryText: '#006783',

  rateOrderHeaderBg: '#F7F9FB',
  rateOrderHeaderTitle: '#006783',
  rateOrderBackIcon: '#006783',
  rateOrderHeaderProfileIcon: '#000000',
  rateOrderCardBg: '#FFFFFF',
  rateOrderThumbBg: '#BDE9FF',
  rateOrderOrderId: '#6D797F',
  rateOrderServiceName: '#191C1E',
  rateOrderCompletedDate: '#3D484E',
  rateOrderHeading: '#191C1E',
  rateOrderSubtitle: '#6D797F',
  rateOrderStarInactive: '#BCC8CF',
  rateOrderStarActive: '#F5A623',
  rateOrderRatingLabel: '#05B0DF',
  rateOrderTagsHeading: '#191C1E',
  rateOrderTagBg: '#F7F9FB',
  rateOrderTagBorder: '#BCC8CF',
  rateOrderTagText: '#3D484E',
  rateOrderTagActiveBg: '#05B0DF',
  rateOrderTagActiveBorder: '#05B0DF',
  rateOrderTagActiveText: '#FFFFFF',
  rateOrderReviewLabel: '#191C1E',
  rateOrderTextareaBg: '#FFFFFF',
  rateOrderTextareaBorder: '#BCC8CF',
  rateOrderTextareaPlaceholder: '#6D797F',
  rateOrderTextareaText: '#191C1E',
  rateOrderSubmitBg: '#05B0DF',
  rateOrderSubmitText: '#FFFFFF',
  rateOrderSkipText: '#006783',
};

export const FONTS = {
  regular: 'PlusJakartaSans-Regular',
  medium: 'PlusJakartaSans-Medium',
  semiBold: 'PlusJakartaSans-SemiBold',
  bold: 'PlusJakartaSans-Bold',
};

export const TYPOGRAPHY = {
  fontFamily: 'Plus Jakarta Sans',
  titleFontSize: 28,
  titleLineHeight: 36,
  titleLetterSpacing: 1.4,
  titleFontWeight: '700',
  subtitleFontSize: 16,
  subtitleLineHeight: 24,
  subtitleLetterSpacing: 0.4,
  subtitleFontWeight: '500',
  logoHeight: 108.28,
};

export const SPACING = {
  contentPaddingHorizontal: 20,
  logoWidth: 280,
  logoMarginBottom: 24,
  typographyGap: 4,
};

export const ONBOARDING_SHARED = {
  headerHeight: 60,
  contentPaddingHorizontal: 20,
  skipButtonPaddingVertical: 8,
  skipButtonPaddingHorizontal: 16,
  skipFontSize: 14,
  skipLineHeight: 20,
  skipLetterSpacing: 0.7,
  bottomAreaPaddingBottom: 32,
  dotsMarginBottom: 24,
  buttonBorderRadius: 16,
  buttonPaddingVertical: 16,
  buttonFontSize: 14,
  buttonLineHeight: 20,
  buttonLetterSpacing: 0.7,
  arrowIconPath:
    'M9.13125 6.75H0V5.25H9.13125L4.93125 1.05L6 0L12 6L6 12L4.93125 10.95L9.13125 6.75Z',
};

export const ONBOARDING = {
  screenWidth: 390,
  skipRowHeight: 60,
  illustrationTop: 16,
  illustrationHeight: 297.5,
  illustrationSize: 297.5,
  blobWidth: 302.5,
  blobHeight: 223.13,
  blobTop: 37.19,
  textContentTop: 346,
  bottomControlsTop: 558,
  contentSideWidth: 350,
  headingFontSize: 28,
  headingLineHeight: 36,
  bodyFontSize: 16,
  bodyLineHeight: 24,
  skipFontSize: 14,
  skipLineHeight: 20,
  skipLetterSpacing: 0.7,
  dotSize: 8,
  dotActiveWidth: 32,
  buttonFontSize: 14,
  buttonLineHeight: 20,
  buttonLetterSpacing: 0.7,
};

export const ONBOARDING2 = {
  screenWidth: 390,
  headerHeight: 54,
  circleTop: 106,
  circleLeft: 39,
  circleSize: 280,
  imageTop: 40,
  imageLeft: 28,
  imageSize: 336,
  contentTop: 374,
  contentPaddingTop: 32,
  contentPaddingHorizontal: 20,
  contentPaddingBottom: 59,
  headingFontSize: 28,
  headingLineHeight: 36,
  headingLetterSpacing: -0.7,
  bodyFontSize: 16,
  bodyLineHeight: 26,
  bodyWidth: 280,
  skipFontSize: 14,
  skipLineHeight: 20,
  skipLetterSpacing: 0.7,
  dotSize: 8,
  dotActiveWidth: 32,
  buttonFontSize: 14,
  buttonLineHeight: 20,
  buttonLetterSpacing: 0.7,
  buttonBorderRadius: 12,
};

export const LOGIN = {
  contentPaddingHorizontal: 21,
  headerTop: 139,
  logoWidth: 160,
  logoHeight: 61.88,
  headingFontSize: 24,
  headingLineHeight: 36.4,
  headingLetterSpacing: -0.7,
  subtitleFontSize: 16,
  subtitleLineHeight: 25.6,
  formGap: 24,
  inputHeight: 56,
  inputBorderRadius: 16,
  countryCodeFontSize: 16,
  countryCodeLineHeight: 25.6,
  placeholderFontSize: 16,
  buttonHeight: 56,
  buttonBorderRadius: 18,
  buttonFontSize: 18,
  buttonLineHeight: 27,
  footerFontSize: 14,
  footerLineHeight: 22.75,
};

export const HOME = {
  headerHeight: 66,
  backgroundGradientHeight: 650,
  sectionHeadingFontSize: 22,
  sectionHeadingLineHeight: 30.8,
  seeAllFontSize: 16,
  seeAllLineHeight: 25.6,

  carouselHeight: 197,
  carouselRadius: 12,
  dotSize: 8,
  dotActiveSize: 13,
  dotGap: 5,

  underlineWidth: 49,
  underlineHeight: 2,
  underlineRadius: 8,
  underlineMarginTop: 6,

  serviceCardBorderWidth: 1,
  serviceCardLabelFontSize: 18,
  serviceCardLabelLineHeight: 31.4,
  smallCardWidth: 128,
  smallCardHeight: 120,
  smallCardRadius: 16,
  smallCardIconSize: 66,
  smallCardIconMarginTop: 14,
  smallCardSelectedBorderWidth: 2,
  smallCardLabelFontSize: 14,
  smallCardLabelLineHeight: 19.6,
  gridCardHeight: 176,
  gridCardRadius: 23,
  gridCardIconSize: 96,
  gridCardIconMarginTop: 15,

  scheduleButtonWidth: 250,
  scheduleButtonHeight: 45,
  scheduleButtonRadius: 8,
  scheduleButtonFontSize: 14,
  scheduleButtonLineHeight: 21.4,

  offerBannerRadius: 12,

  orderCardRadius: 12,
  orderAccentBarWidth: 4,
  orderIdLabelFontSize: 14,
  orderIdLabelLineHeight: 27,
  orderNumberFontSize: 24,
  orderNumberLineHeight: 27,
  orderSubtitleFontSize: 14,
  orderSubtitleLineHeight: 19.6,
  statusPillFontSize: 14,
  statusPillLineHeight: 19.6,
  captionLabelFontSize: 12,
  captionValueFontSize: 16,
  captionLineHeight: 19.6,

  navHeight: 90,
  navLabelFontSize: 12,
  navLabelLineHeight: 19.6,
};

export const SELECT_AREA = {
  headerHeight: 64,
  contentPaddingHorizontal: 20,
  headingFontSize: 22,
  headingLineHeight: 30.8,
  searchInputHeight: 49,
  searchBorderRadius: 12,
  searchFontSize: 16,
  itemFontSize: 16,
  itemLineHeight: 24,
  itemPaddingVertical: 12,
  itemPaddingHorizontal: 16,
  listBorderRadius: 12,
  buttonHeight: 44,
  buttonBorderRadius: 8,
  buttonFontSize: 14,
  buttonLineHeight: 20,
  buttonLetterSpacing: 0.7,
};

export const CHOOSE_STORE = {
  headerHeight: 64,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 32,
  headingFontSize: 22,
  headingLineHeight: 38.4,
  headingLetterSpacing: -0.64,
  cardGap: 24,
  cardPadding: 24,
  cardRadius: 20,
  cardGap2: 16,
  nameFontSize: 18,
  nameLineHeight: 27,
  addressFontSize: 14,
  addressLineHeight: 19.6,
  badgeFontSize: 14,
  badgeLineHeight: 19.6,
  pickupFontSize: 14,
  pickupLineHeight: 19.6,
  buttonFontSize: 16,
  buttonLineHeight: 25.6,
  buttonBorderRadius: 8,
};

export const SERVICES = {
  headerHeight: 64,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 32,
  headingFontSize: 22,
  headingLineHeight: 38.4,
  headingLetterSpacing: -0.64,
  listRadius: 12,
  itemPaddingVertical: 24,
  itemPaddingHorizontal: 24,
  nameFontSize: 18,
  nameLineHeight: 27,
  descriptionFontSize: 16,
  descriptionLineHeight: 25.6,
};

export const SERVICE_DETAIL = {
  headerHeight: 65,
  headingFontSize: 22,
  headingLineHeight: 38.4,
  headingLetterSpacing: -0.64,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 16,

  bannerHeight: 122,
  bannerRadius: 8,

  categoryPillGap: 6,
  categoryPillPaddingVertical: 6,
  categoryPillPaddingHorizontal: 12,
  categoryPillRadius: 9999,
  categoryPillFontSize: 10,
  categoryPillLineHeight: 14.2,
  categoryPillLetterSpacing: 0.5,
  categoryIconSize: 12,

  genderPillGap: 6,
  genderPillPaddingVertical: 6,
  genderPillPaddingHorizontal: 12,
  genderPillRadius: 4,
  genderPillBorderWidth: 1,

  listGap: 12,
  itemCardRadius: 8,
  itemPaddingVertical: 16,
  itemPaddingHorizontal: 16,
  itemNameFontSize: 16.5,
  itemNameLineHeight: 24.75,
  itemDescriptionFontSize: 14.4,
  itemDescriptionLineHeight: 21.7,
  itemPriceFontSize: 16.5,
  itemPriceLineHeight: 24.75,

  addButtonWidth: 76,
  addButtonHeight: 34.5,
  addButtonRadius: 8,
  addButtonBorderWidth: 1,
  addButtonFontSize: 13.4,
  addButtonLineHeight: 20.1,

  checkoutBarPaddingVertical: 16,
  checkoutBarPaddingHorizontal: 32,
  checkoutBarRadius: 9999,
  checkoutBarFontSize: 18,
  checkoutBarLineHeight: 27,
};

export const CART = {
  headerHeight: 66,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 24,
  headingFontSize: 22,
  headingLineHeight: 30.8,
  headingLetterSpacing: -0.55,
  sectionGap: 32,
  cardRadius: 20,
  cardPadding: 24,
  itemHeight: 102,
  itemNameFontSize: 18,
  itemNameLineHeight: 27,
  itemDescFontSize: 14,
  itemDescLineHeight: 19.6,
  itemPriceFontSize: 18,
  itemPriceLineHeight: 27,
  stepperWidth: 93,
  stepperHeight: 42,
  addMoreFontSize: 18,
  addMoreLineHeight: 27,
  inputHeight: 52,
  inputBorderRadius: 12,
  summaryLabelFontSize: 16,
  summaryLabelLineHeight: 25.6,
  totalLabelFontSize: 22,
  totalLabelLineHeight: 30.8,
  totalValueFontSize: 32,
  totalValueLineHeight: 38.4,
  totalValueLetterSpacing: -0.64,
  checkoutBarHeight: 106,
  checkoutButtonRadius: 8,
  checkoutTotalFontSize: 14,
  checkoutTotalLineHeight: 19.6,
  checkoutPriceFontSize: 18,
  checkoutPriceLineHeight: 27,
  checkoutCtaFontSize: 18,
  checkoutCtaLineHeight: 27,
  emptyContentPaddingTop: 64,
  emptyIllustrationWidth: 271,
  emptyIllustrationHeight: 181,
  emptyIllustrationMarginBottom: 32,
  emptyHeadingFontSize: 28,
  emptyHeadingLineHeight: 36.4,
  emptySubtitleFontSize: 16,
  emptySubtitleLineHeight: 25.6,
  emptyButtonPaddingVertical: 16,
  emptyButtonPaddingHorizontal: 48,
  emptyButtonBorderRadius: 12,
  emptyButtonFontSize: 18,
  emptyButtonLineHeight: 27,
};

export const OTP = {
  contentPaddingHorizontal: 24,
  headerTop: 149,
  logoWidth: 140,
  logoHeight: 54,
  headingFontSize: 22,
  headingLineHeight: 30.8,
  subtitleFontSize: 16,
  subtitleLineHeight: 25.6,
  subtitleWidth: 216,
  inputSize: 48,
  inputHeight: 56,
  inputBorderRadius: 8,
  inputFontSize: 20,
  timerFontSize: 16,
  timerLineHeight: 25.6,
  resendFontSize: 16,
  resendLineHeight: 25.6,
  verifyButtonHeight: 56,
  verifyButtonFontSize: 18,
  verifyButtonLineHeight: 27,
  changeEmailFontSize: 16,
  changeEmailLineHeight: 25.6,
};

export const ONBOARDING3 = {
  headerHeight: 48,
  contentPaddingHorizontal: 20,
  illustrationWrapperWidth: 320,
  illustrationSize: 302,
  typographyWidth: 340,
  typographyGap: 16,
  headingFontSize: 28,
  headingLineHeight: 36,
  bodyFontSize: 16,
  bodyLineHeight: 24,
  skipFontSize: 14,
  skipLineHeight: 20,
  skipLetterSpacing: 0.7,
  dotSize: 8,
  dotActiveWidth: 24,
  buttonFontSize: 14,
  buttonLineHeight: 20,
  buttonLetterSpacing: 0.7,
  buttonBorderRadius: 12,
};

export const ADDRESS = {
  headerHeight: 62,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  mapHeight: 192,
  pinSize: 48,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 16,
  sectionGap: 16,
  currentLocationButtonPaddingVertical: 16,
  currentLocationFontSize: 16,
  currentLocationLineHeight: 25.6,
  sectionTitleFontSize: 18,
  sectionTitleLineHeight: 27,
  cardBorderRadius: 20,
  cardPadding: 24,
  cardIconWrapperSize: 48,
  nameFontSize: 16,
  nameLineHeight: 25.6,
  badgeFontSize: 14,
  badgeLineHeight: 19.6,
  addressTextFontSize: 14,
  addressTextLineHeight: 19.6,
  selectedBadgeFontSize: 14,
  selectedBadgeLineHeight: 19.6,
  addButtonHeight: 101,
  addButtonFontSize: 16,
  addButtonLineHeight: 25.6,
  confirmButtonPaddingVertical: 16,
  confirmButtonBorderRadius: 12,
  confirmButtonFontSize: 16,
  confirmButtonLineHeight: 25.6,
};

export const ADD_ADDRESS = {
  headerHeight: 66,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  mapHeight: 256,
  mapBorderRadius: 24,
  pinSize: 48,
  currentLocationButtonPaddingVertical: 16,
  currentLocationFontSize: 16,
  currentLocationLineHeight: 25.6,
  contentPaddingHorizontal: 16,
  cardBorderRadius: 20,
  cardPadding: 24,
  cardTitleFontSize: 18,
  cardTitleLineHeight: 27,
  formGap: 24,
  locationContextRadius: 12,
  locationContextPrimaryFontSize: 16,
  locationContextPrimaryLineHeight: 22.4,
  locationContextSecondaryFontSize: 14,
  locationContextSecondaryLineHeight: 19.6,
  fieldLabelFontSize: 16,
  fieldLabelLineHeight: 25.6,
  fieldGap: 8,
  inputHeight: 52,
  inputBorderRadius: 12,
  inputFontSize: 16,
  labelSelectorGap: 16,
  labelPillPaddingVertical: 10,
  labelPillPaddingHorizontal: 20,
  labelPillFontSize: 12,
  labelPillLineHeight: 17,
  saveButtonHeight: 99,
  saveButtonPaddingVertical: 13,
  saveButtonBorderRadius: 12,
  saveButtonFontSize: 18,
  saveButtonLineHeight: 27,
};

export const SCHEDULE = {
  headerHeight: 65,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 24,
  sectionGap: 32,
  sectionTitleFontSize: 18,
  sectionTitleLineHeight: 27,
  sectionHeaderGap: 16,
  dateCardWidth: 80,
  dateCardHeight: 69,
  dateCardGap: 8,
  dateDayFontSize: 14,
  dateDayLineHeight: 19.6,
  dateNumberFontSize: 22,
  dateNumberLineHeight: 30.8,
  timeSlotGap: 8,
  timeSlotFontSize: 16,
  timeSlotLineHeight: 25.6,
  timeSlotBorderRadius: 12,
  toggleCardBorderRadius: 20,
  toggleCardPadding: 24,
  toggleIconWrapperSize: 48,
  toggleTitleFontSize: 18,
  toggleTitleLineHeight: 27,
  toggleSubtitleFontSize: 14,
  toggleSubtitleLineHeight: 19.6,
  switchWidth: 44,
  switchHeight: 24,
  switchThumbSize: 20,
  notesLabelFontSize: 18,
  notesLabelLineHeight: 27,
  notesOptionalFontSize: 14,
  notesOptionalLineHeight: 19.6,
  notesInputHeight: 106,
  notesInputBorderRadius: 12,
  notesInputFontSize: 16,
  bottomBarHeight: 130,
  continueButtonBorderRadius: 12,
  continueButtonFontSize: 18,
  continueButtonLineHeight: 27,
};

export const PAYMENT = {
  headerHeight: 66,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  contentPaddingHorizontal: 16,
  contentPaddingVertical: 32,
  sectionGap: 32,
  cardBorderRadius: 20,
  cardPadding: 24,
  cardGap: 16,
  orderTitleFontSize: 18,
  orderTitleLineHeight: 27,
  orderIdFontSize: 14,
  orderIdLineHeight: 19.6,
  statusBadgeFontSize: 14,
  statusBadgeLineHeight: 19.6,
  lineItemLabelFontSize: 16,
  lineItemLabelLineHeight: 25.6,
  lineItemValueFontSize: 16,
  lineItemValueLineHeight: 25.6,
  lineItemGap: 8,
  totalLabelFontSize: 18,
  totalLabelLineHeight: 27,
  totalValueFontSize: 22,
  totalValueLineHeight: 30.8,
  sectionTitleFontSize: 18,
  sectionTitleLineHeight: 27,
  methodGap: 16,
  methodBorderRadius: 16,
  methodPadding: 16,
  methodIconWrapperSize: 40,
  methodLabelFontSize: 16,
  methodLabelLineHeight: 25.6,
  methodDetailFontSize: 14,
  methodDetailLineHeight: 19.6,
  cardBadgeWidth: 48,
  cardBadgeHeight: 32,
  radioSize: 20,
  radioDotSize: 10,
  bottomBarHeight: 114,
  payButtonHeight: 58,
  payButtonBorderRadius: 12,
  payButtonLabelFontSize: 18,
  payButtonLabelLineHeight: 27,
};

export const ORDER_CONFIRMED = {
  headerHeight: 66,
  logoWidth: 140,
  logoHeight: 54,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 16,
  badgeOuterSize: 160,
  badgeMidSize: 96,
  badgeInnerSize: 64,
  badgeIconSize: 33.33,
  badgeMarginBottom: 32,
  headingFontSize: 28,
  headingLineHeight: 36.4,
  subtitleFontSize: 16,
  subtitleLineHeight: 25.6,
  subtitleWidth: 260,
  sectionGap: 32,
  cardBorderRadius: 20,
  cardPadding: 24,
  cardGap: 16,
  orderLabelFontSize: 16,
  orderLabelLineHeight: 25.6,
  orderValueFontSize: 18,
  orderValueLineHeight: 27,
  infoBoxBorderRadius: 12,
  infoBoxPadding: 16,
  infoBoxGap: 4,
  infoLabelFontSize: 14,
  infoLabelLineHeight: 19.6,
  infoLabelLetterSpacing: 0.7,
  infoTitleFontSize: 18,
  infoTitleLineHeight: 27,
  infoSubtitleFontSize: 14,
  infoSubtitleLineHeight: 19.6,
  totalLabelFontSize: 22,
  totalLabelLineHeight: 30.8,
  totalValueFontSize: 28,
  totalValueLineHeight: 36.4,
  buttonGap: 16,
  primaryButtonHeight: 58,
  primaryButtonBorderRadius: 12,
  primaryButtonFontSize: 18,
  primaryButtonLineHeight: 27,
  secondaryButtonPaddingVertical: 16,
  secondaryButtonFontSize: 16,
  secondaryButtonLineHeight: 25.6,
};

export const TRACK_ORDER = {
  headerHeight: 66,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 32,
  contentPaddingBottom: 32,
  sectionGap: 32,
  mapSectionGap: 16,
  sectionHeadingFontSize: 18,
  sectionHeadingLineHeight: 25.2,
  orderIdFontSize: 16,
  orderIdLineHeight: 22.4,
  badgeFontSize: 14,
  badgeLineHeight: 19.6,
  badgePaddingVertical: 6,
  badgePaddingHorizontal: 16,
  mapHeight: 300,
  mapBorderRadius: 24,
  etaCardTop: 16,
  etaCardLeft: 16,
  etaCardPaddingVertical: 15,
  etaCardPaddingHorizontal: 20,
  etaCardBorderRadius: 12,
  etaLabelFontSize: 14,
  etaLabelLineHeight: 19.6,
  etaValueFontSize: 28,
  etaUnitFontSize: 18,
  driverCardBottom: 16,
  driverCardLeft: 16,
  driverCardRight: 16,
  driverCardPadding: 16,
  driverCardBorderRadius: 16,
  driverAvatarSize: 48,
  driverNameFontSize: 18,
  driverNameLineHeight: 27,
  driverRatingFontSize: 14,
  driverRatingLineHeight: 19.6,
  callButtonSize: 48,
  cardBorderRadius: 20,
  cardPadding: 24,
  cardHeadingFontSize: 22,
  cardHeadingLineHeight: 30.8,
  stepsGap: 24,
  stepsPaddingLeft: 8,
  stepIconRingSize: 32,
  stepIconSize: 24,
  stepTitleFontSize: 18,
  stepTitleLineHeight: 25.2,
  stepSubtitleFontSize: 14,
  stepSubtitleLineHeight: 19.6,
  supportCardBorderRadius: 20,
  supportCardPadding: 24,
  supportTitleFontSize: 18,
  supportTitleLineHeight: 25.2,
  supportSubtitleFontSize: 14,
  supportSubtitleLineHeight: 19.6,
  supportButtonPaddingVertical: 12,
  supportButtonPaddingHorizontal: 24,
  supportButtonBorderRadius: 12,
  supportButtonFontSize: 18,
  supportButtonLineHeight: 27,
};

export const ORDER_HISTORY = {
  headerHeight: 66,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 32,
  contentPaddingBottom: 32,
  sectionGap: 24,
  chipsBarHeight: 50,
  chipPaddingVertical: 8,
  chipPaddingHorizontal: 24,
  chipFontSize: 16,
  chipLineHeight: 25.6,
  chipGap: 12,
  cardBorderRadius: 20,
  cardPadding: 24,
  cardGap: 16,
  badgePaddingVertical: 4,
  badgePaddingHorizontal: 8,
  badgeFontSize: 14,
  badgeLineHeight: 19.6,
  orderNumberFontSize: 18,
  orderNumberLineHeight: 27,
  orderMetaFontSize: 14,
  orderMetaLineHeight: 19.6,
  priceFontSize: 22,
  priceLineHeight: 30.8,
  serviceRowGap: 8,
  serviceLabelFontSize: 16,
  serviceLabelLineHeight: 25.6,
  actionsGap: 16,
  actionButtonPaddingVertical: 8,
  actionButtonFontSize: 16,
  actionButtonLineHeight: 25.6,
  actionButtonBorderRadius: 8,
  actionButtonIconGap: 4,
};

export const PROFILE = {
  headerHeight: 66,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 16,
  contentPaddingBottom: 32,
  sectionGap: 32,
  bentoGap: 16,
  userCardBorderRadius: 20,
  userCardPadding: 24,
  editButtonSize: 36,
  avatarSize: 96,
  verifiedBadgeSize: 32,
  nameFontSize: 22,
  nameLineHeight: 30.8,
  phoneFontSize: 14,
  phoneLineHeight: 19.6,
  memberBadgeFontSize: 14,
  memberBadgeLineHeight: 19.6,
  memberBadgePaddingVertical: 4,
  memberBadgePaddingHorizontal: 16,
  statCardBorderRadius: 20,
  statCardPadding: 24,
  statIconSize: 40,
  statLabelFontSize: 14,
  statLabelLineHeight: 19.6,
  statValueFontSize: 28,
  statValueLineHeight: 36.4,
  trendFontSize: 14,
  trendLineHeight: 19.6,
  bannerBorderRadius: 20,
  bannerPadding: 16,
  bannerIconSize: 27,
  bannerTitleFontSize: 16,
  bannerTitleLineHeight: 25.6,
  bannerSubtitleFontSize: 14,
  bannerSubtitleLineHeight: 19.6,
  inviteButtonPaddingVertical: 8,
  inviteButtonPaddingHorizontal: 16,
  inviteButtonBorderRadius: 8,
  inviteButtonFontSize: 16,
  inviteButtonLineHeight: 25.6,
  settingsCardBorderRadius: 20,
  settingsHeadingPaddingTop: 24,
  settingsHeadingPaddingBottom: 8,
  settingsHeadingFontSize: 18,
  settingsHeadingLineHeight: 27,
  navIconBoxSize: 32,
  navRowPadding: 16,
  navGap: 16,
  navLabelFontSize: 16,
  navLabelLineHeight: 25.6,
  footerFontSize: 14,
  footerLineHeight: 19.6,
};

export const SUPPORT = {
  headerHeight: 66,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 24,
  contentPaddingBottom: 32,
  sectionGap: 32,
  headingGap: 8,
  headingFontSize: 28,
  headingLineHeight: 36.4,
  subheadingFontSize: 16,
  subheadingLineHeight: 25.6,
  searchInputHeight: 56,
  searchBorderRadius: 12,
  searchFontSize: 16,
  searchIconLeft: 16,
  categoryGridGap: 16,
  categoryCardBorderRadius: 20,
  categoryCardPaddingVertical: 24,
  categoryIconSize: 48,
  categoryLabelFontSize: 18,
  categoryLabelLineHeight: 27,
  ticketsCardBorderRadius: 20,
  ticketsCardPadding: 24,
  ticketsHeadingFontSize: 22,
  ticketsHeadingLineHeight: 30.8,
  viewAllFontSize: 16,
  viewAllLineHeight: 25.6,
  ticketsGap: 8,
  ticketBorderRadius: 12,
  ticketPadding: 16,
  ticketIconSize: 40,
  ticketTitleFontSize: 16,
  ticketTitleLineHeight: 22.4,
  ticketSubtitleFontSize: 14,
  ticketSubtitleLineHeight: 19.6,
  statusPillFontSize: 12,
  statusPillLineHeight: 16,
  statusPillPaddingVertical: 3,
  statusPillPaddingHorizontal: 8,
  ctaCardBorderRadius: 20,
  ctaCardPadding: 32,
  ctaCardGap: 24,
  ctaIconWrapperSize: 96,
  ctaOnlineDotSize: 16,
  ctaTitleFontSize: 22,
  ctaTitleLineHeight: 30.8,
  ctaSubtitleFontSize: 16,
  ctaSubtitleLineHeight: 25.6,
  ctaButtonsGap: 16,
  ctaButtonPaddingVertical: 16,
  ctaButtonBorderRadius: 12,
  ctaButtonFontSize: 16,
  ctaButtonLineHeight: 25.6,
  responseTimeFontSize: 14,
  responseTimeLineHeight: 19.6,
};

export const NOTIFICATIONS = {
  headerHeight: 66,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 16,
  contentPaddingBottom: 32,
  sectionGap: 24,
  headingFontSize: 28,
  headingLineHeight: 36.4,
  markAllReadFontSize: 16,
  markAllReadLineHeight: 25.6,
  chipGap: 12,
  chipPaddingVertical: 8,
  chipPaddingHorizontal: 24,
  chipFontSize: 16,
  chipLineHeight: 25.6,
  listGap: 16,
  cardBorderRadius: 20,
  cardPadding: 24,
  cardGap: 16,
  iconSize: 48,
  titleFontSize: 18,
  titleLineHeight: 27,
  timeFontSize: 14,
  timeLineHeight: 19.6,
  bodyFontSize: 14,
  bodyLineHeight: 19.6,
  actionFontSize: 16,
  actionLineHeight: 25.6,
};

export const SETTINGS = {
  headerHeight: 66,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 28,
  contentPaddingBottom: 32,
  sectionGap: 20,
  headingGap: 8,
  headingFontSize: 28,
  headingLineHeight: 36.4,
  subheadingFontSize: 16,
  subheadingLineHeight: 25.6,
  sectionHeadingFontSize: 18,
  sectionHeadingLineHeight: 27,
  sectionGroupGap: 16,
  cardBorderRadius: 12,
  rowPadding: 24,
  rowIconSize: 40,
  rowTitleFontSize: 16,
  rowTitleLineHeight: 25.6,
  rowSubtitleFontSize: 14,
  rowSubtitleLineHeight: 19.6,
  switchWidth: 48,
  switchHeight: 24,
  switchThumbSize: 20,
  logoutPaddingVertical: 16,
  logoutBorderRadius: 12,
  logoutFontSize: 16,
  logoutLineHeight: 25.6,
  footerFontSize: 14,
  footerLineHeight: 19.6,
};

export const NOT_FOUND = {
  headerHeight: 66,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 30.8,
  contentPaddingHorizontal: 16,
  illustrationWidth: 286,
  illustrationHeight: 191,
  illustrationMarginBottom: 32,
  headingFontSize: 28,
  headingLineHeight: 36.4,
  headingMarginBottom: 16,
  subtitleFontSize: 16,
  subtitleLineHeight: 25.6,
  subtitleMaxWidth: 290,
  buttonsGap: 16,
  buttonsMarginTop: 32,
  buttonPaddingVertical: 16,
  buttonBorderRadius: 12,
  buttonFontSize: 18,
  buttonLineHeight: 27,
  buttonGap: 8,
};

export const RATE_ORDER = {
  headerHeight: 66,
  headerTitleFontSize: 22,
  headerTitleLineHeight: 27,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 32,
  contentPaddingBottom: 32,
  sectionGap: 32,
  cardBorderRadius: 20,
  cardPadding: 24,
  cardGap: 20,
  thumbSize: 96,
  thumbBorderRadius: 12,
  orderIdFontSize: 14,
  orderIdLineHeight: 19.6,
  serviceNameFontSize: 22,
  serviceNameLineHeight: 30.8,
  completedDateFontSize: 14,
  completedDateLineHeight: 20,
  headingFontSize: 28,
  headingLineHeight: 36.4,
  subtitleFontSize: 16,
  subtitleLineHeight: 25.6,
  starsGap: 8,
  starSize: 30,
  ratingLabelFontSize: 18,
  ratingLabelLineHeight: 27,
  tagsHeadingFontSize: 18,
  tagsHeadingLineHeight: 27,
  tagsGap: 12,
  tagPaddingVertical: 8,
  tagPaddingHorizontal: 16,
  tagFontSize: 16,
  tagLineHeight: 25.6,
  reviewLabelFontSize: 18,
  reviewLabelLineHeight: 27,
  textareaMinHeight: 120,
  textareaBorderRadius: 12,
  textareaFontSize: 16,
  textareaLineHeight: 25.6,
  submitButtonHeight: 56,
  submitButtonBorderRadius: 12,
  submitButtonFontSize: 18,
  submitButtonLineHeight: 27,
  skipButtonHeight: 48,
  skipButtonFontSize: 16,
  skipButtonLineHeight: 25.6,
};

export const SPLASH = {
  garmentWrapperSize: 160,
  garmentIconSize: 120,
  sparkleWrapperSize: 160,
  logoWidth: 176,
  logoHeight: 68,
  logoGlowSize: 200,
  logoMarginTop: 28,
  titleFontSize: 30,
  titleLineHeight: 38,
  titleLetterSpacing: 3,
  subtitleFontSize: 15,
  subtitleLineHeight: 22,
  subtitleLetterSpacing: 0.4,
  subtitleMarginTop: 8,
  backgroundGlowSize: 340,
  blobBlueSize: 260,
  blobGreenSize: 300,
  contentUpwardOffset: 22,
  foldedExitTranslateY: -18,
  ambientGlowDuration: 600,
  garmentStageDuration: 500,
  foldedRevealDuration: 400,
  taglineRevealDelay: 150,
  taglineRevealDuration: 300,
  holdBeforeNavigate: 350,
  glowPulseDuration: 700,
};

export const STORE_SERVICES = {
  headerHeight: 74,
  headerTitleFontSize: 18,
  headerTitleLineHeight: 25.2,
  headerSubtitleFontSize: 13,
  headerSubtitleLineHeight: 18.2,
  tabBarPaddingVertical: 12,
  tabBarPaddingHorizontal: 14,
  tabChipGap: 10,
  tabChipPaddingVertical: 9,
  tabChipPaddingHorizontal: 14,
  tabChipBorderRadius: 20,
  tabIconSize: 16,
  tabGap: 6,
  tabFontSize: 13,
  tabLineHeight: 18.2,
  contentPaddingHorizontal: 16,
  contentPaddingTop: 16,
  itemPaddingVertical: 16,
  itemNameFontSize: 16,
  itemNameLineHeight: 22.4,
  itemDescFontSize: 13,
  itemDescLineHeight: 18.2,
  itemGap: 4,
  priceFontSize: 17,
  priceLineHeight: 23.8,
  controlWidth: 92,
  controlHeight: 34,
  controlBorderRadius: 8,
  addPillFontSize: 13,
  stepperButtonSize: 26,
  stepperQuantityFontSize: 14,
  rowGap: 16,
  cardBorderRadius: 20,
  cardPadding: 20,
  cartBarHeight: 76,
  cartBarBorderRadius: 16,
  cartBarPaddingHorizontal: 20,
  cartBarTextFontSize: 14,
  cartBarTextLineHeight: 19.6,
  cartBarButtonPaddingVertical: 10,
  cartBarButtonPaddingHorizontal: 20,
  cartBarButtonFontSize: 14,
  cartBarButtonLineHeight: 19.6,
};
